# Site settings
titol: Pareu de parar-me
email: your-email@example.com
descripcio: Campanya de SOS Racisme contra les identificacions per motius racials
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SOSRacis
google_analytics: UA-XXXXX-X # change UA-XXXXX-X to be your site's ID

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
plugins_dir:
  - jekyll-menus
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Outputting
permalink: pretty
paginate: 2
timezone: Europe/Madrid
lang: 'ca'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Where things are
source: src
destination: _site
images_path: assets/img
theme_scripts_path: assets/scripts
theme_styles_path: assets/styles
theme_fonts_path: assets/fonts
data_dir: _data
paginate_path: "/blog/page:num/"


# Collections
collections:
  homepage:
      output: false
  manifest:
      output: false
  actua:
      output: false
  videos:
      output: true
  posts:
      output: true
  twitter:
      output: false

# Site defaults frontmatters
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: basic
      sections: collection-name
      titular: Títol per la capçalera de la pàgina
      imatge_titular: landing-1.jpg
      titol: Títol per SEO
      descripcio: "Descripció per SEO"
      paraules_clau: "Paraules clau separades per comes"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "homepage"
    values:
      include: homepage/section.html
      order: 1
      titol_seccio: Títol de la secció
