# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pareudepararme.org" # the base hostname & protocol for your site, e.g. http://example.com
site_url:
  ca: "https://www.pareudepararme.org"
  es: "https://www.paraddepararme.org"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-paginate-v2
exclude:
  - functions
  - node_modules
  - src/functions
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - netlify.toml
  - package-lock.json
  - package.json
  - README.md
include:
  - _redirects

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Outputting
permalink: pretty
timezone: Europe/Madrid
lang: "ca"

# Where things are
source: .
destination: _site
images_path: assets/img
docs_path: assets/img
theme_scripts_path: assets/scripts
theme_styles_path: assets/styles
theme_fonts_path: assets/fonts
data_dir: _data

# Collections
collections:
  c05-twitter-campanya:
  c05-twitter-campana:
  c06-guia-ca:
  c06-guia-es:
  c07-informe-2018-ca:
  c07-informe-2018-es:
  c07-informe-2021-ca:
  c07-informe-2021-es:
  c03-testimonis:
    output: true
  c03-testimonios:
    output: true
  c04-noticies:
    output: true
  c04-noticias:
    output: true

# Site defaults frontmatters
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: basic
      titol:
      locale: ca
      ref: referencia_unica

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection:

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 4

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/pag/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category:

  # Optional, the default tag to use, omit to disable
  tag: ""

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ca

  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2 # The number of links before the current page
    after: 2 # The number of links after the current page

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index"
############################################################
