# Site settings
titol: Pareu de parar-me
email: your-email@example.com
descripcio: Campanya de SOS Racisme contra les identificacions per motius racials
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SOSRacis
google_analytics: UA-XXXXX-X # change UA-XXXXX-X to be your site's ID

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
plugins_dir:
  - jekyll-menus
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Outputting
permalink: pretty
paginate: 2
timezone: Europe/Madrid
lang: 'ca'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Where things are
source: src
destination: _site
images_path: assets/img
theme_scripts_path: assets/scripts
theme_styles_path: assets/styles
theme_fonts_path: assets/fonts
data_dir: _data
paginate_path: "/blog/page:num/"


# Collections
collections:
  homepage:
      output: false
  manifest-page:
      output: false
  videos:
      output: true
  posts:
      output: true
  twitter-page:
      output: false

# Site defaults frontmatters
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: basic
      sections: collection-name
      titular: Títol per la capçalera de la pàgina
      imatge_titular: landing-1.jpg
      titol: Títol per SEO
      descripcio: "Descripció per SEO"
      paraules_clau: "Paraules clau separades per comes"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "videos"
    values:
      layout: videosingle
      order: 1
      titol: Títol del vídeo
      codi_youtube: xxxxxxxxxxx
      date: 2016-10-20 12:25:00
      descripcio: Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem.
      paraules_clau: paraula1, paraula2
      detalls:
        - camp: Data i hora de la parada
          valor: dd/mm/aaaa, 00:00h
        - camp: Lloc de la parada
          valor: Carrer, Ciutat
        - camp: L'agent va comunicar el motiu de la parada?
          valor: Sí/No
        - camp: L'agent es va identificar?
          valor: Sí/No
        - camp: L'agent anava uniformat o de paisà?
          valor: Uniformat/De paisà
        - camp: Hi va haver un escorcoll de la roba després de la identificació?
          valor: Sí/No
        - camp: Hi va haver violència verbal o física durant el procediment d'identificació i registre?
          valor: Sí/No
        - camp: Hi va haver una detenció posterior?
          valor: Sí/No
        - camp: Era la primera vegada que l'identificaven?
          valor: Sí/No
