---
active: true
ca:
  text: " Vols comunicar una parada policial per perfilació racial?"
  text_link: " Descàrrega l'app"
  link: https://play.google.com/store/apps/details?id=org.pareudepararme.pareu_de_pararme_map
es:
  text: "¿Quieres comunicar una parada por perfilación racial?"
  text_link: "¡Descárgate la APP!"
  link: https://play.google.com/store/apps/details?id=org.pareudepararme.pareu_de_pararme_map
