---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: "./_c01-inici"
  label: C01 inici
  create: all
  match: "**/*"
- type: directory
  path: "./_c01-inicio"
  label: C01 inicio
  create: all
  match: "**/*"
- type: directory
  path: "./_c02-manifest"
  label: C02 manifest
  create: all
  match: "**/*"
- type: directory
  path: "./_c02-manifiesto"
  label: C02 manifiesto
  create: all
  match: "**/*"
- type: directory
  path: "./_c03-testimonis"
  label: C03 testimonis
  create: all
  match: "**/*"
- type: directory
  path: "./_c03-testimonios"
  label: C03 testimonios
  create: all
  match: "**/*"
- type: directory
  path: "./_c04-noticies"
  label: C04 noticies
  create: all
  match: "**/*"
- type: directory
  path: "./_c04-noticias"
  label: C04 noticias
  create: all
  match: "**/*"
- type: directory
  path: "./_c05-twitter-campanya"
  label: C05 twitter campanya
  create: all
  match: "**/*"
- type: directory
  path: "./_c05-twitter-campana"
  label: C05 twitter campana
  create: all
  match: "**/*"
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: "/assets/img"
use_front_matter_path: false
file_template: ":filename:"
