backend:
  name: git-gateway
  branch: master

display_url: https://www.pareudepararme.org

media_folder: "assets/img" # Media files will be stored in the repo under assets/img
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /assets/img

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "noticies"
    label: "Notícies-CA"
    label_singular: "Notícia"
    description: "Notícies en llengua catalana."
    folder: "_c04-noticies"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/noticies/:path/"}
      - {label: "Idioma", name: "locale", widget: "hidden", default: "ca"}
      - {label: "Publicada", name: "published", widget: "boolean", default: false, hint: "La notícia només serà pública si activeu aquesta opció"}
      - {label: "Títol URL", name: "title", widget: "string", hint: "Títol breu per construir la URL de la notícia", pattern: [".{10,100}", "El títol ha de tenir entre 10 i 100 caracters"]}
      - {label: "Titular", name: "titol", widget: "string", hint: "Títol de la notícia"}
      - {label: "Imatge", name: "imatge", widget: "image", hint: "Imatge principal. Ha de pesar menys de 5MB, i tenir dimensions mínimes de 300x157 i màximes de 4096x4096 pixels"}
      - {label: "Descripció imatge", name: "imatge_alt", widget: "string", hint: "Breu descripció de la imatge"}
      - {label: "Referència", name: "ref", widget: "string", hint: "Identificador únic de la notícia. Cal que sigui el mateix en tots els idiomes", pattern: ["[a-z_\\-]+", "Format: referencia_unica"]}
      - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", hint: "Data que apareixerà com a data de publicació"}
      - {label: "Contingut", name: "body", widget: "markdown", hint: "El contingut de la notícia"}
    editor:
      preview: false

  - name: "noticias"
    label: "Noticias-ES"
    label_singular: "Noticia"
    description: "Noticias en lengua española."
    folder: "_c04-noticias"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/noticias/:path/"}
      - {label: "Idioma", name: "locale", widget: "hidden", default: "es"}
      - {label: "Publicada", name: "published", widget: "boolean", default: false, hint: "La noticia sólo será pública si activas esta opción"}
      - {label: "Título URL", name: "title", widget: "string", hint: "Título breve para construir la URL de la noticia", pattern: [".{10,100}", "El título debe tener entre 10 y 100 caracteres"]}
      - {label: "Titular", name: "titol", widget: "string", hint: "Título de la noticia"}
      - {label: "Imagen", name: "imatge", widget: "image", hint: "Imagen principal. Debe pesar menos de 5MB, y tener dimensiones mínimas de 300x157 y máximas de 4096x4096 pixels"}
      - {label: "Descripción imagen", name: "imatge_alt", widget: "string", hint: "Breve descripción de la imagen"}
      - {label: "Referencia", name: "ref", widget: "string", hint: "Identificador único de la noticia. Debe ser el mismo en todos los idiomas", pattern: ["[a-z_\\-]+", "Formato: referencia_unica"]}
      - {label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", hint: "Fecha que aparecerá como fecha de publicación"}
      - {label: "Contenido", name: "body", widget: "markdown", hint: "El contenido de la noticia"}
    editor:
      preview: false
