backend:
  name: git-gateway
  branch: master

display_url: https://www.pareudepararme.org

media_folder: "assets/img" # Media files will be stored in the repo under assets/img
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /assets/img

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "noticies"
    label: "Notícies-CA"
    label_singular: "Notícia CA"
    description: "Notícies en llengua catalana."
    folder: "_c04-noticies"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/noticies/:path/"}
      - {label: "Idioma", name: "locale", widget: "hidden", default: "ca"}
      - {label: "Publicada", name: "published", widget: "boolean", default: false, hint: "La notícia només serà pública si activeu aquesta opció"}
      - {label: "Títol URL", name: "title", widget: "string", hint: "Títol breu per construir la URL de la notícia", pattern: [".{10,100}", "El títol ha de tenir entre 10 i 100 caracters"]}
      - {label: "Titular", name: "titol", widget: "string", hint: "Títol de la notícia"}
      - {label: "Imatge", name: "imatge", widget: "image", hint: "Imatge principal. Ha de pesar menys de 5MB, i tenir dimensions mínimes de 300x157 i màximes de 4096x4096 pixels"}
      - {label: "Descripció imatge", name: "imatge_alt", widget: "string", hint: "Breu descripció de la imatge"}
      - {label: "Referència", name: "ref", widget: "string", hint: "Identificador únic de la notícia. Cal que sigui el mateix en tots els idiomes", pattern: ["[a-z_\\-]+", "Format: referencia_unica"]}
      - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", hint: "Data que apareixerà com a data de publicació"}
      - {label: "Contingut", name: "body", widget: "markdown", hint: "El contingut de la notícia"}
    editor:
      preview: false

  - name: "noticias"
    label: "Noticias-ES"
    label_singular: "Noticia ES"
    description: "Noticias en lengua española."
    folder: "_c04-noticias"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/noticias/:path/"}
      - {label: "Idioma", name: "locale", widget: "hidden", default: "es"}
      - {label: "Publicada", name: "published", widget: "boolean", default: false, hint: "La noticia sólo será pública si activas esta opción"}
      - {label: "Título URL", name: "title", widget: "string", hint: "Título breve para construir la URL de la noticia", pattern: [".{10,100}", "El título debe tener entre 10 y 100 caracteres"]}
      - {label: "Titular", name: "titol", widget: "string", hint: "Título de la noticia"}
      - {label: "Imagen", name: "imatge", widget: "image", hint: "Imagen principal. Debe pesar menos de 5MB, y tener dimensiones mínimas de 300x157 y máximas de 4096x4096 pixels"}
      - {label: "Descripción imagen", name: "imatge_alt", widget: "string", hint: "Breve descripción de la imagen"}
      - {label: "Referencia", name: "ref", widget: "string", hint: "Identificador único de la noticia. Debe ser el mismo en todos los idiomas", pattern: ["[a-z_\\-]+", "Formato: referencia_unica"]}
      - {label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", hint: "Fecha que aparecerá como fecha de publicación"}
      - {label: "Contenido", name: "body", widget: "markdown", hint: "El contenido de la noticia"}
    editor:
      preview: false

  - name: "testimonis"
    label: "Testimonis-CA"
    label_singular: "Testimoni CA"
    description: "Testimonis en llengua catalana."
    folder: "_c03-testimonis"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "videosingle"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/testimonis/:path/"}
      - {label: "Idioma", name: "locale", widget: "hidden", default: "ca"}
      - {label: "Publicada", name: "published", widget: "boolean", default: false, hint: "El testimoni només serà públic si activeu aquesta opció"}
      - {label: "Títol URL", name: "title", widget: "string", hint: "Títol breu per construir la URL del testimoni", pattern: [".{10,100}", "El títol ha de tenir entre 10 i 100 caracters"]}
      - {label: "Títol", name: "titol", widget: "string", hint: "Títol del testimoni"}
      - {label: "ID YouTube", name: "codi_youtube", widget: "string", hint: "Identificador del vídeo a YouTube: https://www.youtube.com/watch?v=ID-YOUTUBE"}
      - {label: "SEO-Descripció", name: "descripcio", widget: "string", hint: "Breu descripció del cas"}
      - {label: "SEO-Paraules clau", name: "paraules_clau", widget: "string", hint: "Paraules separades per comes que descriguin el contingut del testimoni"}
      - {label: "SEO-Imatge xarxes", name: "imatge", widget: "image", default: "/assets/img/logo-catala-fons.jpg", hint: "Imatge associada. Ha de pesar menys de 5MB, i tenir dimensions mínimes de 300x157 i màximes de 4096x4096 pixels"}
      - {label: "Referencia", name: "ref", widget: "string", hint: "Identificador únic del testimoni. Cal que sigui el mateix en tots els idiomes", pattern: ["[a-z_\\-]+", "Format: referencia_unica"]}
      - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", hint: "Data que apareixerà com a data de publicació"}
      - label: "Qüestionari"
        name: "detalls"
        widget: "object"
        fields:
          - {label: "Q1-Data", name: "data_label", widget: "string", default: "Data i hora de la parada"}
          - {label: "A1-Data", name: "data", widget: "datetime", format: "DD/MM/YYYY, HH:mm"}
          - {label: "Q2-Lloc", name: "lloc_label", widget: "string", default: "Lloc de la parada"}
          - {label: "A2-Lloc", name: "lloc", widget: "string", hint: "Format: Carrer o Barri, Ciutat"}
          - {label: "Q3-Motiu", name: "motiu_label", widget: "string", default: "L'agent va comunicar el motiu de la parada?"}
          - {label: "A3-Motiu", name: "motiu", widget: "boolean", default: false}
          - {label: "Q4-Identificació", name: "identificar_label", widget: "string", default: "L'agent es va identificar?"}
          - {label: "A4-Identificació", name: "identificar", widget: "boolean", default: false}
          - {label: "Q5-Uniformat", name: "uniformat_label", widget: "string", default: "L'agent anava uniformat?"}
          - {label: "A5-Uniformat", name: "uniformat", widget: "boolean", default: false}
          - {label: "Q6-Escorcoll", name: "escorcoll_label", widget: "string", default: "Hi va haver un escorcoll de la roba després de la identificació?"}
          - {label: "A6-Escorcoll", name: "escorcoll", widget: "boolean", default: false}
          - {label: "Q7-Violència", name: "violencia_label", widget: "string", default: "Hi va haver violència verbal o física durant el procediment d'identificació i registre?"}
          - {label: "A7-Violència", name: "violencia", widget: "boolean", default: false}
          - {label: "Q8-Detenció", name: "detencio_label", widget: "string", default: "Hi va haver una detenció posterior?"}
          - {label: "A8-Detenció", name: "detencio", widget: "boolean", default: false}
          - {label: "Q9-Primera Vegada", name: "vegada_label", widget: "string", default: "Era la primera vegada que l'identificaven?"}
          - {label: "A9-Primera Vegada", name: "vegada", widget: "boolean", default: false}
      - {label: "Contingut", name: "body", widget: "markdown", hint: "Contingut del testimoni"}

  - name: "testimonios"
    label: "Testimonios-ES"
    label_singular: "Testimonio ES"
    description: "Testimonios en lengua española."
    folder: "_c03-testimonios"
    create: true
    extension: "md"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "videosingle"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/testimonios/:path/"}
      - {label: "Idioma", name: "locale", widget: "hidden", default: "es"}
      - {label: "Publicada", name: "published", widget: "boolean", default: false, hint: "El testimonio sólo será público si activas esta opción"}
      - {label: "Título URL", name: "title", widget: "string", hint: "Título breve para construir la URL del testimonio", pattern: [".{10,100}", "El título debe tener entre 10 y 100 caracteres"]}
      - {label: "Título", name: "titol", widget: "string", hint: "Título del testimonio"}
      - {label: "ID YouTube", name: "codi_youtube", widget: "string", hint: "Identificador del vídeo en YouTube: https://www.youtube.com/watch?v=ID-YOUTUBE"}
      - {label: "SEO-Descripción", name: "descripcio", widget: "string", hint: "Breve descripción del caso"}
      - {label: "SEO-Palabras clave", name: "paraules_clau", widget: "string", hint: "Palabras separadas por comas que describan el contenido del testimonio"}
      - {label: "SEO-Imagen redes", name: "imatge", widget: "image", default: "/assets/img/logo-castella-fons.jpg", hint: "Imagen asociada. Debe pesar menos de 5MB, y tener dimensiones mínimas de 300x157 y máximas de 4096x4096 pixels"}
      - {label: "Referencia", name: "ref", widget: "string", hint: "Identificador único del testimonio. Debe ser el mismo en todos los idiomas", pattern: ["[a-z_\\-]+", "Formato: referencia_unica"]}
      - {label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", hint: "Fecha que aparecerá como fecha de publicación"}
      - label: "Qüestionario"
        name: "detalls"
        widget: "object"
        fields:
          - {label: "Q1-Fecha", name: "data_label", widget: "string", default: "Fecha y hora de la identificación"}
          - {label: "A1-Fecha", name: "data", widget: "datetime", format: "DD/MM/YYYY, HH:mm"}
          - {label: "Q2-Lugar", name: "lloc_label", widget: "string", default: "Lugar de la identificación"}
          - {label: "A2-Lugar", name: "lloc", widget: "string", hint: "Formato: Calle o Barrio, Ciudad"}
          - {label: "Q3-Motivo", name: "motiu_label", widget: "string", default: "¿Le comunicó el agente el motivo de la identificación?"}
          - {label: "A3-Motivo", name: "motiu", widget: "boolean", default: false}
          - {label: "Q4-Identificación", name: "identificar_label", widget: "string", default: "¿Se identificó el agente?"}
          - {label: "A4-Identificación", name: "identificar", widget: "boolean", default: false}
          - {label: "Q5-Uniformado", name: "uniformat_label", widget: "string", default: "¿El agente estaba uniformado?"}
          - {label: "A5-Uniformado", name: "uniformat", widget: "boolean", default: false}
          - {label: "Q6-Cacheo", name: "escorcoll_label", widget: "string", default: "¿Hubo cacheo después de la identificación?"}
          - {label: "A6-Cacheo", name: "escorcoll", widget: "boolean", default: false}
          - {label: "Q7-Violencia", name: "violencia_label", widget: "string", default: "¿Hubo violencia verbal o física durante el procedimiento de identificación y registro?"}
          - {label: "A7-Violencia", name: "violencia", widget: "boolean", default: false}
          - {label: "Q8-Detención", name: "detencio_label", widget: "string", default: "¿Se realizó detención posterior?"}
          - {label: "A8-Detención", name: "detencio", widget: "boolean", default: false}
          - {label: "Q9-Primera Vez", name: "vegada_label", widget: "string", default: "¿Era la primera vez que lo identificaban?"}
          - {label: "A9-Primera Vez", name: "vegada", widget: "boolean", default: false}
      - {label: "Contingut", name: "body", widget: "markdown", hint: "Contenido del testimonio"}
